### ISSUE TITLE
Useless switch cases and incorrect messaging in http client 

### ISSUE THREAD

**Issue by chaffneue** [bshaffer/php-echonest-api#12]
HttpClient.php 

  /**
     \* Get a JSON response and transform it to a PHP array
     *
     \* @return  array   the response
     */
    protected function decodeResponse($response)
    {
        switch ($this->options['format'])
        {
            case 'json':
                return json_decode($response, true);

```
        case 'jsonp':
            throw new LogicException("format 'jsonp' not yet supported by this library");

        case 'xml':
            throw new LogicException("format 'xml' not yet supported by this library");

        case 'xspf':
            throw new LogicException("format 'xspf' not yet supported by this library");
    }

    throw new LogicException(__CLASS__.' only supports json, json, xml, and xspf formats, '.$this->options['format'].' given.');
}
```

This should be refactored sometime as the documentation is all wrong and the exception handling is also wrong, leading to confusing errors at runtime. perhaps just use a separate method for each type as you add them, right now it's kind of YAGNI. At this point, there's no reason to offer other formats, which would save you a bunch of lines of useless code for handling unsupported formats.

**Comment by bshaffer** [comment]
Can you explain what you mean by "all wrong"?

Also, json, jsonp, and xml are supported by the echonest API, and so supported by this API library.  Explain how this is YAGNI?

**Comment by chaffneue** [comment]
Sure. regardless of Echonest's API supporting the other formats, If you look at the messaging thrown by the logic exception at the bottom it says **CLASS**.' only supports json, json, xml, and xspf formats, '.$this->options['format'].' given.' - attempts to use anything other results in an exception saying format not yet supported by this library. You may as well remove the crufty switch cases and change the logic exception to say class only supports json. 

This method only really needs to do one thing and that is get a php associative array. The other formats are superfluous to that goal. At this point, you may as well just hardcode it to 'json' in the request as changing the format using setOption  will cause side effects needing exception handling. 

Another option would be to give users a getRawResponse() accessor or something like that, so your class could still be useful for getting XML (which I wanted in the first place) instead of building in a decode into the request method, which throws an exception no matter what when using xml.

**Comment by bshaffer** [comment]
The switch statement serves as a reminder to support those formats in the future.  It is not meant to be a long term solution.

Feel free to fork the API and add support for XML, as that is the real issue in question here.
